import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'he' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.portfolioUpdate': 'Portfolio Update',
    'nav.settings': 'Settings',
    'nav.logs': 'Logs',
    'nav.admin': 'Admin',
    'nav.signOut': 'Sign Out',
    'nav.appName': 'Portfolio Ammo',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.totalValue': 'Total Value',
    'dashboard.snp': 'S&P / SPY',
    'dashboard.ta125': 'TA-125',
    'dashboard.cashAmmo': 'Cash (Ammo)',
    'dashboard.target': 'Target',
    'dashboard.equitiesCash': 'Equities / Cash',
    'dashboard.portfolioAllocation': 'Portfolio Allocation',
    'dashboard.currentDistribution': 'Current asset distribution',
    'dashboard.noAllocationData': 'No allocation data yet',
    'dashboard.addFirstUpdate': 'Add Your First Update',
    'dashboard.latestNotification': 'Latest Notification',
    'dashboard.notificationsAppear': 'Notifications appear here when you receive strategy recommendations',
    'dashboard.welcomeTitle': 'Welcome to Portfolio Ammo!',
    'dashboard.welcomeDescription': 'Get started in 2 simple steps to track your portfolio and get smart rebalancing recommendations.',
    'dashboard.step1Title': 'Configure your strategy',
    'dashboard.step1Description': 'Set your target allocation and ammo triggers',
    'dashboard.goToSettings': 'Go to Settings →',
    'dashboard.step2Title': 'Enter your portfolio values',
    'dashboard.step2Description': 'Add your current holdings and contributions',
    'dashboard.createFirstUpdate': 'Create First Update →',

    // Update page
    'update.title': 'Portfolio Update',
    'update.subtitle': 'Record your contributions and get a recommendation',
    'update.currentPortfolio': 'Current Portfolio Values',
    'update.updateHoldings': 'Update your current holdings',
    'update.editValues': 'Edit Values',
    'update.cancel': 'Cancel',
    'update.totalPortfolioValue': 'Total Portfolio Value',
    'update.newContribution': 'New Contribution',
    'update.contributionDescription': 'Enter your total contribution – it will be split according to your target allocation',
    'update.totalContribution': 'Total Contribution',
    'update.currency': 'Currency',
    'update.targetAllocation': 'Target Allocation',
    'update.contributionBreakdown': 'Contribution Breakdown',
    'update.marketData': 'Market Data',
    'update.loadingMarket': 'Loading market data...',
    'update.price': 'Price',
    'update.high52w': '52W High',
    'update.drawdown': 'Drawdown',
    'update.recommendation': 'Recommendation',
    'update.saveUpdate': 'Save Update',
    'update.saving': 'Saving...',
    'update.settingsRequired': 'Settings Required',
    'update.configureSettings': 'Please configure your settings before creating an update.',
    'update.updateSaved': 'Update saved with recommendation!',
    'update.contributionsSaved': 'Contributions saved',
    'update.marketUnavailable': 'Market data unavailable – recommendation not generated',
    'update.spyProxy': 'SPY (S&P 500)',
    'update.eisProxy': 'EIS (Israel ETF / TA-125 proxy)',

    // Settings page
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure your long-term strategy parameters',
    'settings.profile': 'Profile',
    'settings.profileDescription': 'Manage your profile information',
    'settings.email': 'Email',
    'settings.emailCannotChange': 'Email cannot be changed',
    'settings.fullName': 'Full Name',
    'settings.enterFullName': 'Enter your full name',
    'settings.updateName': 'Update Name',
    'settings.nameUpdated': 'Name updated successfully!',
    'settings.nameEmpty': 'Name cannot be empty',
    'settings.nameTooLong': 'Name must be less than 100 characters',
    'settings.emailNotifications': 'Email Notifications',
    'settings.testEmailSetup': 'Test your email notification setup',
    'settings.sendTestEmail': 'Send Test Email',
    'settings.testEmailSent': 'Test email sent!',
    'settings.checkInbox': 'Check your inbox at',
    'settings.targetAllocation': 'Target Allocation',
    'settings.allocationDescription': 'Your ideal portfolio balance (must equal 100%)',
    'settings.total': 'Total',
    'settings.mustEqual100': 'Must equal 100%',
    'settings.cashThresholds': 'Cash Thresholds',
    'settings.cashThresholdsDescription': 'Define cash allocation boundaries',
    'settings.cashMin': 'Cash Min (%)',
    'settings.cashTarget': 'Cash Target (%)',
    'settings.setInTargetAllocation': 'Set in Target Allocation',
    'settings.cashMax': 'Cash Max (%)',
    'settings.ammoTriggers': 'Ammo Triggers',
    'settings.ammoTriggersDescription': 'Market drawdown thresholds to deploy cash (each tranche = 1/3 of current cash)',
    'settings.tranche1': 'Tranche 1 (%)',
    'settings.tranche2': 'Tranche 2 (%)',
    'settings.tranche3': 'Tranche 3 (%)',
    'settings.rebuildThreshold': 'Rebuild Threshold (%)',
    'settings.rebuildThresholdDescription': 'When drawdown falls below this, start rebuilding ammo',
    'settings.saveSettings': 'Save Settings',
    'settings.saved': 'Settings saved!',
    'settings.resetAmmo': 'Reset Ammo',
    'settings.resetAmmoTitle': 'Reset Ammo Status',
    'settings.resetAmmoDescription': 'This will reset all ammo tranches to "Ready" status.',
    'settings.doesNotMoveMoney': 'This does NOT move any money.',
    'settings.onlyResetsStatus': 'This only resets tranche status to Ready.',
    'settings.resetAmmoUseCase': 'Use this when the previous market cycle is complete and cash has rebuilt to target.',
    'settings.confirmReset': 'I understand this is a logical reset only',
    'settings.ammoReset': 'Ammo state reset to Ready!',
    'settings.allocationMustEqual100': 'Target allocations must sum to 100%',
    'settings.snpPercent': 'SNP (%)',
    'settings.ta125Percent': 'TA125 (%)',
    'settings.cashPercent': 'Cash (%)',

    // Logs page
    'logs.title': 'Recommendation Logs',
    'logs.subtitle': 'History of all strategy recommendations',
    'logs.allRecommendations': 'All Recommendations',
    'logs.totalEntries': 'total entries',
    'logs.noRecommendations': 'No recommendations yet. Create your first monthly update!',
    'logs.date': 'Date',
    'logs.type': 'Type',
    'logs.status': 'Status',
    'logs.drawdown': 'Drawdown',
    'logs.amount': 'Amount',
    'logs.recommendation': 'Recommendation',

    // Admin page
    'admin.title': 'Admin Panel',
    'admin.refresh': 'Refresh',
    'admin.inviteUser': 'Invite User',
    'admin.email': 'Email',
    'admin.name': 'Name',
    'admin.nameOptional': 'Name (optional)',
    'admin.role': 'Role',
    'admin.sendInvite': 'Send Invite',
    'admin.users': 'Users',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.pending': 'Pending',
    'admin.active': 'Active',
    'admin.owner': 'Owner',
    'admin.admin': 'Admin',
    'admin.user': 'User',
    'admin.deleteUser': 'Delete User',
    'admin.deleteUserConfirm': 'Are you sure you want to delete',
    'admin.deleteUserWarning': 'This will permanently remove the user and all their data. This action cannot be undone.',
    'admin.delete': 'Delete',
    'admin.accessDenied': 'Access Denied',
    'admin.adminRequired': 'Admin access required',
    'admin.invitationSent': 'Invitation sent successfully',
    'admin.roleUpdated': 'Role updated successfully',
    'admin.userDeleted': 'deleted successfully',
    'admin.noUsers': 'No users found',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.success': 'Success',
    'common.refresh': 'Refresh',

    // Market status
    'market.normal': 'Normal',
    'market.correction': 'Correction',
    'market.bear': 'Bear Market',
    'market.crash': 'Crash',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications',

    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',

    // Strategy recommendations
    'strategy.stopCashOverMax': 'Cash allocation ({currentCash}%) exceeds maximum ({maxCash}%). Stop contributing to cash - direct all contributions to equities.',
    'strategy.fireAmmo3': 'Significant downturn detected ({drawdown}% drawdown). Deploy Tranche 3: 1/3 of current cash ({amount}) to equities.',
    'strategy.fireAmmo2': 'Bear market conditions ({drawdown}% drawdown). Deploy Tranche 2: 1/3 of current cash ({amount}) to equities.',
    'strategy.fireAmmo1': 'Market correction detected ({drawdown}% drawdown). Deploy Tranche 1: 1/3 of current cash ({amount}) to equities.',
    'strategy.rebuildAmmo': 'Market recovered ({drawdown}% drawdown). Rebuild cash reserves to {target}%. Transfer {amount} from equities to cash.',
    'strategy.normal': 'Market normal ({drawdown}% drawdown). Split contribution: {cashContrib} to cash, {stocksContrib} to equities.',
  },
  he: {
    // Navigation
    'nav.dashboard': 'לוח בקרה',
    'nav.portfolioUpdate': 'עדכון תיק',
    'nav.settings': 'הגדרות',
    'nav.logs': 'היסטוריה',
    'nav.admin': 'ניהול',
    'nav.signOut': 'התנתק',
    'nav.appName': 'Portfolio Ammo',

    // Dashboard
    'dashboard.title': 'לוח בקרה',
    'dashboard.welcome': 'ברוך הבא',
    'dashboard.totalValue': 'שווי כולל',
    'dashboard.snp': 'S&P / SPY',
    'dashboard.ta125': 'ת"א-125',
    'dashboard.cashAmmo': 'מזומן (תחמושת)',
    'dashboard.target': 'יעד',
    'dashboard.equitiesCash': 'מניות / מזומן',
    'dashboard.portfolioAllocation': 'הקצאת תיק',
    'dashboard.currentDistribution': 'התפלגות נכסים נוכחית',
    'dashboard.noAllocationData': 'אין נתוני הקצאה עדיין',
    'dashboard.addFirstUpdate': 'הוסף עדכון ראשון',
    'dashboard.latestNotification': 'התראה אחרונה',
    'dashboard.notificationsAppear': 'התראות יופיעו כאן כשתקבל המלצות אסטרטגיה',
    'dashboard.welcomeTitle': 'ברוכים הבאים ל-Portfolio Ammo!',
    'dashboard.welcomeDescription': 'התחל ב-2 צעדים פשוטים כדי לעקוב אחר התיק ולקבל המלצות איזון חכמות.',
    'dashboard.step1Title': 'הגדר את האסטרטגיה שלך',
    'dashboard.step1Description': 'קבע את הקצאת היעד וטריגרי התחמושת',
    'dashboard.goToSettings': 'עבור להגדרות ←',
    'dashboard.step2Title': 'הזן את ערכי התיק',
    'dashboard.step2Description': 'הוסף את ההחזקות הנוכחיות והתרומות',
    'dashboard.createFirstUpdate': 'צור עדכון ראשון ←',

    // Update page
    'update.title': 'עדכון תיק',
    'update.subtitle': 'רשום את ההפקדות שלך וקבל המלצה',
    'update.currentPortfolio': 'שווי תיק נוכחי',
    'update.updateHoldings': 'עדכן את ההחזקות הנוכחיות',
    'update.editValues': 'ערוך ערכים',
    'update.cancel': 'ביטול',
    'update.totalPortfolioValue': 'שווי תיק כולל',
    'update.newContribution': 'הפקדה חדשה',
    'update.contributionDescription': 'הזן את סכום ההפקדה הכולל – הוא יחולק לפי הקצאת היעד שלך',
    'update.totalContribution': 'סכום הפקדה',
    'update.currency': 'מטבע',
    'update.targetAllocation': 'הקצאת יעד',
    'update.contributionBreakdown': 'פירוט הפקדה',
    'update.marketData': 'נתוני שוק',
    'update.loadingMarket': 'טוען נתוני שוק...',
    'update.price': 'מחיר',
    'update.high52w': 'שיא 52 שבועות',
    'update.drawdown': 'ירידה',
    'update.recommendation': 'המלצה',
    'update.saveUpdate': 'שמור עדכון',
    'update.saving': 'שומר...',
    'update.settingsRequired': 'נדרשות הגדרות',
    'update.configureSettings': 'אנא הגדר את ההגדרות שלך לפני יצירת עדכון.',
    'update.updateSaved': 'עדכון נשמר עם המלצה!',
    'update.contributionsSaved': 'הפקדות נשמרו',
    'update.marketUnavailable': 'נתוני שוק לא זמינים – המלצה לא נוצרה',
    'update.spyProxy': 'SPY (S&P 500)',
    'update.eisProxy': 'EIS (תעודת סל ישראל / מתאם ת"א-125)',

    // Settings page
    'settings.title': 'הגדרות',
    'settings.subtitle': 'הגדר את פרמטרי האסטרטגיה ארוכת הטווח',
    'settings.profile': 'פרופיל',
    'settings.profileDescription': 'נהל את פרטי הפרופיל שלך',
    'settings.email': 'אימייל',
    'settings.emailCannotChange': 'לא ניתן לשנות אימייל',
    'settings.fullName': 'שם מלא',
    'settings.enterFullName': 'הזן את שמך המלא',
    'settings.updateName': 'עדכן שם',
    'settings.nameUpdated': 'השם עודכן בהצלחה!',
    'settings.nameEmpty': 'השם לא יכול להיות ריק',
    'settings.nameTooLong': 'השם חייב להיות פחות מ-100 תווים',
    'settings.emailNotifications': 'התראות אימייל',
    'settings.testEmailSetup': 'בדוק את הגדרת התראות האימייל',
    'settings.sendTestEmail': 'שלח אימייל בדיקה',
    'settings.testEmailSent': 'אימייל בדיקה נשלח!',
    'settings.checkInbox': 'בדוק את תיבת הדואר שלך ב',
    'settings.targetAllocation': 'הקצאת יעד',
    'settings.allocationDescription': 'איזון התיק האידיאלי שלך (חייב להסתכם ב-100%)',
    'settings.total': 'סה"כ',
    'settings.mustEqual100': 'חייב להיות 100%',
    'settings.cashThresholds': 'ספי מזומן',
    'settings.cashThresholdsDescription': 'הגדר גבולות הקצאת מזומן',
    'settings.cashMin': 'מזומן מינימום (%)',
    'settings.cashTarget': 'מזומן יעד (%)',
    'settings.setInTargetAllocation': 'מוגדר בהקצאת יעד',
    'settings.cashMax': 'מזומן מקסימום (%)',
    'settings.ammoTriggers': 'טריגרי תחמושת',
    'settings.ammoTriggersDescription': 'ספי ירידת שוק לפריסת מזומן (כל שלב = 1/3 מהמזומן הנוכחי)',
    'settings.tranche1': 'שלב 1 (%)',
    'settings.tranche2': 'שלב 2 (%)',
    'settings.tranche3': 'שלב 3 (%)',
    'settings.rebuildThreshold': 'סף בנייה מחדש (%)',
    'settings.rebuildThresholdDescription': 'כשהירידה יורדת מתחת לזה, התחל לבנות מחדש תחמושת',
    'settings.saveSettings': 'שמור הגדרות',
    'settings.saved': 'ההגדרות נשמרו!',
    'settings.resetAmmo': 'אפס תחמושת',
    'settings.resetAmmoTitle': 'איפוס מצב תחמושת',
    'settings.resetAmmoDescription': 'זה יאפס את כל שלבי התחמושת למצב "מוכן".',
    'settings.doesNotMoveMoney': 'זה לא מעביר כסף.',
    'settings.onlyResetsStatus': 'זה רק מאפס את מצב השלבים למוכן.',
    'settings.resetAmmoUseCase': 'השתמש בזה כשמחזור השוק הקודם הסתיים והמזומן נבנה מחדש ליעד.',
    'settings.confirmReset': 'אני מבין שזה איפוס לוגי בלבד',
    'settings.ammoReset': 'מצב התחמושת אופס למוכן!',
    'settings.allocationMustEqual100': 'הקצאות היעד חייבות להסתכם ב-100%',
    'settings.snpPercent': 'SNP (%)',
    'settings.ta125Percent': 'ת"א-125 (%)',
    'settings.cashPercent': 'מזומן (%)',

    // Logs page
    'logs.title': 'יומן המלצות',
    'logs.subtitle': 'היסטוריית כל המלצות האסטרטגיה',
    'logs.allRecommendations': 'כל ההמלצות',
    'logs.totalEntries': 'רשומות סה"כ',
    'logs.noRecommendations': 'אין המלצות עדיין. צור את העדכון החודשי הראשון שלך!',
    'logs.date': 'תאריך',
    'logs.type': 'סוג',
    'logs.status': 'סטטוס',
    'logs.drawdown': 'ירידה',
    'logs.amount': 'סכום',
    'logs.recommendation': 'המלצה',

    // Admin page
    'admin.title': 'פאנל ניהול',
    'admin.refresh': 'רענן',
    'admin.inviteUser': 'הזמן משתמש',
    'admin.email': 'אימייל',
    'admin.name': 'שם',
    'admin.nameOptional': 'שם (אופציונלי)',
    'admin.role': 'תפקיד',
    'admin.sendInvite': 'שלח הזמנה',
    'admin.users': 'משתמשים',
    'admin.status': 'סטטוס',
    'admin.actions': 'פעולות',
    'admin.pending': 'ממתין',
    'admin.active': 'פעיל',
    'admin.owner': 'בעלים',
    'admin.admin': 'מנהל',
    'admin.user': 'משתמש',
    'admin.deleteUser': 'מחק משתמש',
    'admin.deleteUserConfirm': 'האם אתה בטוח שברצונך למחוק את',
    'admin.deleteUserWarning': 'זה ימחק לצמיתות את המשתמש ואת כל הנתונים שלו. לא ניתן לבטל פעולה זו.',
    'admin.delete': 'מחק',
    'admin.accessDenied': 'הגישה נדחתה',
    'admin.adminRequired': 'נדרשת גישת מנהל',
    'admin.invitationSent': 'ההזמנה נשלחה בהצלחה',
    'admin.roleUpdated': 'התפקיד עודכן בהצלחה',
    'admin.userDeleted': 'נמחק בהצלחה',
    'admin.noUsers': 'לא נמצאו משתמשים',

    // Common
    'common.loading': 'טוען...',
    'common.error': 'שגיאה',
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.delete': 'מחק',
    'common.edit': 'ערוך',
    'common.close': 'סגור',
    'common.confirm': 'אישור',
    'common.yes': 'כן',
    'common.no': 'לא',
    'common.success': 'הצלחה',
    'common.refresh': 'רענן',

    // Market status
    'market.normal': 'רגיל',
    'market.correction': 'תיקון',
    'market.bear': 'שוק דובי',
    'market.crash': 'קריסה',

    // Notifications
    'notifications.title': 'התראות',
    'notifications.markAllRead': 'סמן הכל כנקרא',
    'notifications.noNotifications': 'אין התראות',

    // Auth
    'auth.signIn': 'התחבר',
    'auth.signUp': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.forgotPassword': 'שכחת סיסמה?',
    'auth.noAccount': 'אין לך חשבון?',
    'auth.hasAccount': 'יש לך חשבון?',

    // Strategy recommendations
    'strategy.stopCashOverMax': 'הקצאת מזומן ({currentCash}%) חורגת מהמקסימום ({maxCash}%). הפסק להפקיד למזומן - הפנה את כל ההפקדות למניות.',
    'strategy.fireAmmo3': 'זוהתה ירידה משמעותית ({drawdown}% ירידה). פרוס שלב 3: 1/3 מהמזומן הנוכחי ({amount}) למניות.',
    'strategy.fireAmmo2': 'תנאי שוק דובי ({drawdown}% ירידה). פרוס שלב 2: 1/3 מהמזומן הנוכחי ({amount}) למניות.',
    'strategy.fireAmmo1': 'זוהה תיקון שוק ({drawdown}% ירידה). פרוס שלב 1: 1/3 מהמזומן הנוכחי ({amount}) למניות.',
    'strategy.rebuildAmmo': 'השוק התאושש ({drawdown}% ירידה). בנה מחדש עתודות מזומן ל-{target}%. העבר {amount} ממניות למזומן.',
    'strategy.normal': 'שוק רגיל ({drawdown}% ירידה). חלק הפקדה: {cashContrib} למזומן, {stocksContrib} למניות.',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель',
    'nav.portfolioUpdate': 'Обновление портфеля',
    'nav.settings': 'Настройки',
    'nav.logs': 'История',
    'nav.admin': 'Админ',
    'nav.signOut': 'Выйти',
    'nav.appName': 'Portfolio Ammo',

    // Dashboard
    'dashboard.title': 'Панель',
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.totalValue': 'Общая стоимость',
    'dashboard.snp': 'S&P / SPY',
    'dashboard.ta125': 'TA-125',
    'dashboard.cashAmmo': 'Наличные (резерв)',
    'dashboard.target': 'Цель',
    'dashboard.equitiesCash': 'Акции / Наличные',
    'dashboard.portfolioAllocation': 'Распределение портфеля',
    'dashboard.currentDistribution': 'Текущее распределение активов',
    'dashboard.noAllocationData': 'Пока нет данных о распределении',
    'dashboard.addFirstUpdate': 'Добавить первое обновление',
    'dashboard.latestNotification': 'Последнее уведомление',
    'dashboard.notificationsAppear': 'Уведомления появятся здесь при получении рекомендаций по стратегии',
    'dashboard.welcomeTitle': 'Добро пожаловать в Portfolio Ammo!',
    'dashboard.welcomeDescription': 'Начните с 2 простых шагов, чтобы отслеживать портфель и получать умные рекомендации по ребалансировке.',
    'dashboard.step1Title': 'Настройте стратегию',
    'dashboard.step1Description': 'Установите целевое распределение и триггеры резервов',
    'dashboard.goToSettings': 'Перейти к настройкам →',
    'dashboard.step2Title': 'Введите значения портфеля',
    'dashboard.step2Description': 'Добавьте текущие активы и вклады',
    'dashboard.createFirstUpdate': 'Создать первое обновление →',

    // Update page
    'update.title': 'Обновление портфеля',
    'update.subtitle': 'Запишите ваши вклады и получите рекомендацию',
    'update.currentPortfolio': 'Текущая стоимость портфеля',
    'update.updateHoldings': 'Обновите ваши текущие активы',
    'update.editValues': 'Редактировать',
    'update.cancel': 'Отмена',
    'update.totalPortfolioValue': 'Общая стоимость портфеля',
    'update.newContribution': 'Новый вклад',
    'update.contributionDescription': 'Введите общую сумму вклада – она будет распределена согласно целевому распределению',
    'update.totalContribution': 'Сумма вклада',
    'update.currency': 'Валюта',
    'update.targetAllocation': 'Целевое распределение',
    'update.contributionBreakdown': 'Распределение вклада',
    'update.marketData': 'Рыночные данные',
    'update.loadingMarket': 'Загрузка рыночных данных...',
    'update.price': 'Цена',
    'update.high52w': 'Макс. 52 нед.',
    'update.drawdown': 'Просадка',
    'update.recommendation': 'Рекомендация',
    'update.saveUpdate': 'Сохранить',
    'update.saving': 'Сохранение...',
    'update.settingsRequired': 'Требуются настройки',
    'update.configureSettings': 'Пожалуйста, настройте параметры перед созданием обновления.',
    'update.updateSaved': 'Обновление сохранено с рекомендацией!',
    'update.contributionsSaved': 'Вклады сохранены',
    'update.marketUnavailable': 'Рыночные данные недоступны – рекомендация не сгенерирована',
    'update.spyProxy': 'SPY (S&P 500)',
    'update.eisProxy': 'EIS (Израильский ETF / прокси TA-125)',

    // Settings page
    'settings.title': 'Настройки',
    'settings.subtitle': 'Настройте параметры долгосрочной стратегии',
    'settings.profile': 'Профиль',
    'settings.profileDescription': 'Управление информацией профиля',
    'settings.email': 'Email',
    'settings.emailCannotChange': 'Email нельзя изменить',
    'settings.fullName': 'Полное имя',
    'settings.enterFullName': 'Введите ваше полное имя',
    'settings.updateName': 'Обновить имя',
    'settings.nameUpdated': 'Имя успешно обновлено!',
    'settings.nameEmpty': 'Имя не может быть пустым',
    'settings.nameTooLong': 'Имя должно быть менее 100 символов',
    'settings.emailNotifications': 'Email уведомления',
    'settings.testEmailSetup': 'Проверить настройку email уведомлений',
    'settings.sendTestEmail': 'Отправить тестовый email',
    'settings.testEmailSent': 'Тестовый email отправлен!',
    'settings.checkInbox': 'Проверьте почту на',
    'settings.targetAllocation': 'Целевое распределение',
    'settings.allocationDescription': 'Идеальный баланс портфеля (должен равняться 100%)',
    'settings.total': 'Итого',
    'settings.mustEqual100': 'Должно быть 100%',
    'settings.cashThresholds': 'Лимиты наличных',
    'settings.cashThresholdsDescription': 'Определите границы распределения наличных',
    'settings.cashMin': 'Мин. наличные (%)',
    'settings.cashTarget': 'Цель наличных (%)',
    'settings.setInTargetAllocation': 'Установлено в целевом распределении',
    'settings.cashMax': 'Макс. наличные (%)',
    'settings.ammoTriggers': 'Триггеры резервов',
    'settings.ammoTriggersDescription': 'Пороги просадки рынка для развертывания наличных (каждый транш = 1/3 текущих наличных)',
    'settings.tranche1': 'Транш 1 (%)',
    'settings.tranche2': 'Транш 2 (%)',
    'settings.tranche3': 'Транш 3 (%)',
    'settings.rebuildThreshold': 'Порог восстановления (%)',
    'settings.rebuildThresholdDescription': 'Когда просадка упадет ниже этого, начать восстанавливать резервы',
    'settings.saveSettings': 'Сохранить настройки',
    'settings.saved': 'Настройки сохранены!',
    'settings.resetAmmo': 'Сбросить резервы',
    'settings.resetAmmoTitle': 'Сброс статуса резервов',
    'settings.resetAmmoDescription': 'Это сбросит все транши резервов в статус "Готов".',
    'settings.doesNotMoveMoney': 'Это НЕ перемещает деньги.',
    'settings.onlyResetsStatus': 'Это только сбрасывает статус траншей в Готов.',
    'settings.resetAmmoUseCase': 'Используйте это когда предыдущий рыночный цикл завершен и наличные восстановлены до цели.',
    'settings.confirmReset': 'Я понимаю, что это только логический сброс',
    'settings.ammoReset': 'Статус резервов сброшен в Готов!',
    'settings.allocationMustEqual100': 'Целевые распределения должны составлять 100%',
    'settings.snpPercent': 'SNP (%)',
    'settings.ta125Percent': 'TA125 (%)',
    'settings.cashPercent': 'Наличные (%)',

    // Logs page
    'logs.title': 'Журнал рекомендаций',
    'logs.subtitle': 'История всех стратегических рекомендаций',
    'logs.allRecommendations': 'Все рекомендации',
    'logs.totalEntries': 'всего записей',
    'logs.noRecommendations': 'Пока нет рекомендаций. Создайте первое ежемесячное обновление!',
    'logs.date': 'Дата',
    'logs.type': 'Тип',
    'logs.status': 'Статус',
    'logs.drawdown': 'Просадка',
    'logs.amount': 'Сумма',
    'logs.recommendation': 'Рекомендация',

    // Admin page
    'admin.title': 'Панель администратора',
    'admin.refresh': 'Обновить',
    'admin.inviteUser': 'Пригласить',
    'admin.email': 'Email',
    'admin.name': 'Имя',
    'admin.nameOptional': 'Имя (необязательно)',
    'admin.role': 'Роль',
    'admin.sendInvite': 'Отправить',
    'admin.users': 'Пользователи',
    'admin.status': 'Статус',
    'admin.actions': 'Действия',
    'admin.pending': 'Ожидание',
    'admin.active': 'Активен',
    'admin.owner': 'Владелец',
    'admin.admin': 'Админ',
    'admin.user': 'Пользователь',
    'admin.deleteUser': 'Удалить пользователя',
    'admin.deleteUserConfirm': 'Вы уверены, что хотите удалить',
    'admin.deleteUserWarning': 'Это навсегда удалит пользователя и все его данные. Это действие нельзя отменить.',
    'admin.delete': 'Удалить',
    'admin.accessDenied': 'Доступ запрещен',
    'admin.adminRequired': 'Требуется доступ администратора',
    'admin.invitationSent': 'Приглашение успешно отправлено',
    'admin.roleUpdated': 'Роль успешно обновлена',
    'admin.userDeleted': 'успешно удален',
    'admin.noUsers': 'Пользователи не найдены',

    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.close': 'Закрыть',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.success': 'Успешно',
    'common.refresh': 'Обновить',

    // Market status
    'market.normal': 'Нормальный',
    'market.correction': 'Коррекция',
    'market.bear': 'Медвежий рынок',
    'market.crash': 'Обвал',

    // Notifications
    'notifications.title': 'Уведомления',
    'notifications.markAllRead': 'Отметить все как прочитанные',
    'notifications.noNotifications': 'Нет уведомлений',

    // Auth
    'auth.signIn': 'Войти',
    'auth.signUp': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',

    // Strategy recommendations
    'strategy.stopCashOverMax': 'Доля наличных ({currentCash}%) превышает максимум ({maxCash}%). Прекратите вклады в наличные - направляйте все вклады в акции.',
    'strategy.fireAmmo3': 'Обнаружен значительный спад ({drawdown}% просадка). Разверните Транш 3: 1/3 текущих наличных ({amount}) в акции.',
    'strategy.fireAmmo2': 'Условия медвежьего рынка ({drawdown}% просадка). Разверните Транш 2: 1/3 текущих наличных ({amount}) в акции.',
    'strategy.fireAmmo1': 'Обнаружена коррекция рынка ({drawdown}% просадка). Разверните Транш 1: 1/3 текущих наличных ({amount}) в акции.',
    'strategy.rebuildAmmo': 'Рынок восстановился ({drawdown}% просадка). Восстановите резервы наличных до {target}%. Переведите {amount} из акций в наличные.',
    'strategy.normal': 'Рынок в норме ({drawdown}% просадка). Разделите вклад: {cashContrib} в наличные, {stocksContrib} в акции.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    // Replace parameters like {param} with actual values
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(value));
      });
    }
    
    return text;
  };

  const dir = language === 'he' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
