import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface AmmoAlertRequest {
  email: string;
  recommendation_type: string;
  recommendation_text: string;
  drawdown_percent: number;
  transfer_amount: number | null;
  market_status: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      email, 
      recommendation_type, 
      recommendation_text, 
      drawdown_percent, 
      transfer_amount,
      market_status 
    }: AmmoAlertRequest = await req.json();

    console.log("Sending ammo alert to:", email, "Type:", recommendation_type);

    const statusColors: Record<string, string> = {
      normal: "#22c55e",
      correction: "#eab308",
      bear: "#f97316",
      crash: "#ef4444",
    };

    const statusColor = statusColors[market_status] || "#6b7280";
    const amountText = transfer_amount ? `$${transfer_amount.toLocaleString()}` : "N/A";

    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #0f172a; color: #e2e8f0; padding: 40px 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #1e293b; border-radius: 12px; padding: 32px; border: 1px solid #334155;">
    <h1 style="color: #f8fafc; margin-top: 0; font-size: 24px;">Portfolio Ammo Alert</h1>
    
    <div style="background-color: ${statusColor}20; border-left: 4px solid ${statusColor}; padding: 16px; border-radius: 0 8px 8px 0; margin: 24px 0;">
      <p style="margin: 0; font-size: 18px; font-weight: 600; color: ${statusColor};">
        ${recommendation_type.replace(/_/g, " ")}
      </p>
      <p style="margin: 8px 0 0; color: #cbd5e1;">
        Market Status: <strong style="color: ${statusColor};">${market_status.toUpperCase()}</strong>
      </p>
    </div>

    <div style="background-color: #0f172a; border-radius: 8px; padding: 20px; margin: 24px 0;">
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 8px 0; color: #94a3b8;">Drawdown</td>
          <td style="padding: 8px 0; text-align: right; color: #ef4444; font-weight: 600;">-${drawdown_percent.toFixed(1)}%</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8;">Transfer Amount</td>
          <td style="padding: 8px 0; text-align: right; color: #22c55e; font-weight: 600;">${amountText}</td>
        </tr>
      </table>
    </div>

    <p style="color: #e2e8f0; line-height: 1.6; margin: 24px 0;">
      ${recommendation_text}
    </p>

    <hr style="border: none; border-top: 1px solid #334155; margin: 24px 0;">

    <p style="color: #64748b; font-size: 12px; margin-bottom: 0;">
      This alert was generated by Portfolio Ammo Tracker. Log in to your dashboard to take action.
    </p>
  </div>
</body>
</html>`;

    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Portfolio Ammo <onboarding@resend.dev>",
        to: [email],
        subject: `AMMO ALERT: ${recommendation_type.replace(/_/g, " ")}`,
        html: htmlContent,
      }),
    });

    const data = await emailResponse.json();

    if (!emailResponse.ok) {
      throw new Error(data.message || "Failed to send email");
    }

    console.log("Email sent successfully:", data);

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: unknown) {
    console.error("Error in send-ammo-alert function:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
};

serve(handler);
